# Sample configuration of data to be parsed for simulation
#---
#random: bool - turn random generator on or off
#randomSeed: int
#numMotes: int
#x_coord: int
#y_coord: int
#terrain: string
---
random: true
randomSeed: 65432
numMotes: 5
x_coord: 1
y_coord: 1
---
random: true
randomSeed: 87654
numMotes: 2
x_coord: 1
y_coord: 1
